theme: jekyll-theme-cayman

navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Code Review"
    url: "/code-review/"
  - title: "Software Design and Engineering"
    url: "/software-design-engineering/"
  - title: "Algorithms and Data Structure"
    url: "/algorithms-data-structure/"
  - title: "Database"
    url: "/database/"